### ISSUE TITLE
Initial featureset

### ISSUE THREAD

**Issue by boennemann** [hoodiehq/pouchdb-hoodie-api#2]
- [x] `store.add(object)`
- [x] `store.add([object1, object2])`
- [x] `store.find(id)`
- [x] `store.find([id1, id2]])`
- [x] `store.find(object) // with id property`
- [x] `store.find([object1, object2]) // with id property`
- [x] `store.find([object1, id2])`
- [x] `store.findOrAdd(id, object)`
- [x] `store.findOrAdd(object)`
- [x] `store.findOrAdd([object1, object2])` 
- [x] `store.findAll()`
- [x] `store.findAll(filterFunction)`
- [x] `store.update(id, changedProperties)`
- [x] `store.update(id, updateFunction)`
- [x] `store.update([id1, id2], changedProperties)`
- [x] `store.update([id1, id2], updateFunction)`
- [x] `store.update(object)`
- [x] `store.update(object, updateFunction)`
- [x] `store.update([object1, object2])`
- [x] `store.update([object1, object2], updateFunction)`
- [x] `store.updateOrAdd(id, object)` #17
- [x] `store.updateOrAdd(object)` #17
- [x] `store.updateOrAdd([object1, object2])` #17
- [x] `store.updateAll(changedProperties)`
- [x] `store.updateAll(updateFunction)`
- [x] `store.remove(id)`
- [x] `store.remove([id1, id2])` #18
- [x] `store.remove(object)`
- [x] `store.remove([object1, object2])` #18
- [x] `store.removeAll()` #19
- [x] `store.removeAll(filterFunction)` #19
- [x] `store.clear()` (https://github.com/boennemann/pouchdb-hoodie-api/issues/2#issuecomment-77747282)

**Comment by gr2m** [comment]
I think `store.clear()` is obsolete for the current scope of `pouchdb-hoodie-api`. It will do the same as `store.removeAll()`, only more efficient as it'd drop the database directly, without manually deleting the objects using the bulk API.

`store.clear()` becomes necessary when we add events, as it would delete all data without triggering `remove` events. But as events are currently out of scope, we can drop it for the initial feature set I'd say
